name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pixi-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pixi and enable caching of the env
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          # optional: pin a version e.g. '0.24.1'
          pixi-version: 'latest'
          cache: true

      # Verify verilator version
      - name: Verify Verilator (task)
          run: pixi run verilator-version